---
output: word_document
---
#440 Reproducibility and Statistics Assignment Homework

<!-- This is an Rmd comment. -->
<!--
You can make comments several lines long by inserting
the text in between the the start and the end of the 
comment.

Comments are where I'll tell you what to do. You should
use the space directly below the comments to do what
the comment asks. You should also describe what you're
doing to make it obvious to the reader so they can
easily follow your logic in a fully reproducible way.
For any statistical tests you run, you should explain
the results in plain English and present the statistics
as you would in an APA style manuscript. For any symbols
you don't know how to use/can't use, feel free to use the name
instead (e.g. alpha)
--> 
<!-- Load the politics.csv data file-->

```{r}
politics<-read.csv("politics.csv")
```

Check the structure.
subject, party, testtime, minwage, and sex need to be factors.
optimismscore and income should be integer and numeric vectors.
Fix any variables that aren't right.
-->
```{r}
str(politics)
```
```{r}
politics$subject<-factor(politics$subject)
politics$testtime<-factor(politics$testtime, levels=c("pre", "post"))
```
<!-- Find the minimum, mean, and variance for posttest
optimism scores. -->
```{r}
summary(politics$optimism)
```
<!-- Create a histogram of posttest optimism scores.
Feel free to use the default ugly settings since
we didn't cover how to do this in ggplot2. If
you're a real go-getter, see if you can figure
out how to make a prettier histogram with better
labels, etc. using ggplot2. -->

```{r}
hist(politics$optimism[politics$testtime=="post"])

```
<!-- Run a test to determine whether political affiliation
is independent of one's gender.
Present the data supporting your analyses in graphical or
tabular form.
-->
```{r}
table(politics$party[politics$testtime=="pre"],politics$sex[politics$testtime=="pre"])
```
```{r}
chisq.test(politics$party[politics$testtime=="pre"],politics$sex[politics$testtime=="pre"])
```
Political affiliation is independent of one's gender, Chi-square(2)= .72674, p=.6953

<!-- Run a test to determine whether or not males and females
have different incomes.
Create a graph to display your data that includes the relevant
means and standard errors.-->
```{r}
t.test(politics$income[politics$sex=="male"& politics$testtime=="pre"], politics$income[politics$sex=="female" & politics$testtime=="pre"])
```

```{r}
library("dplyr")
temp<-politics[politics$testtime=="pre",]%>%group_by(sex)%>%summarize(means=mean(income),
sems=sd(income)/sqrt(length(income)))

library ("ggplot2")
f<-ggplot(temp,aes(x=factor(sex),y=means))+
    geom_bar(stat="identity",color="black",fill=c("deeppink","deepskyblue2"))+geom_errorbar(aes(ymax=means+sems,ymin=means-sems),width=.1)
f                    
```
```{r}
f<-f+ggtitle("video income scores by sex")+
  labs(x="sex", y="pretest income\n(higher=more income")+
  scale_x_discrete(breaks=c("female","male"),labels=c("Female","Male"))+
  theme(plot.title=element_text(size=15,face="bold",vjust=.5))+
  theme(axis.title.x=element_text(size=12,face="bold",vjust=-.25))+
  theme(axis.title.y=element_text(size=12,face="bold",vjust=1))+
  theme(axis.text.x=element_text(size=10,face="bold",color="black"))+
  theme(axis.text.y=element_text(size=10,face="bold",color="black"))+
  coord_cartesian(ylim=c(min(temp$means)-2*max(temp$sems),max(temp$means)+2*max(temp$sems)))+
  theme(panel.border=element_blank(),axis.line=element_line())+
  theme(panel.grid.major.x=element_blank())+
  theme(panel.grid.major.y=element_line(color="darkgrey"))+
  theme(panel.grid.minor.y=element_blank())
f
```
<!-- See if male and females with different political affiliations
have different posttest optimism scores. Create a graph to display
your data that includes the relevant means and standard errors.-->
```{r}
summary(aov(optimismscore~party*sex,data=politics[politics$testtime=="pre",]))
temp<-politics[politics$testtime=="pre",]%>%group_by(party,sex)%>%
    summarize(means=mean(optimismscore),sems=sd(optimismscore)/sqrt(length(optimismscore)))
library("gplots")
col1=col2hex("deeppink")
col2=col2hex("deepskyblue2")
f<-ggplot(temp, aes(x=party, y=means, fill=sex))+
    geom_bar(stat="identity",position=position_dodge())+
    scale_fill_manual(values=c(col1,col2),name="Sex",breaks=c("female","male"),labels=c("Female", "Male"))+
    theme(legend.key=element_rect(color="black"))+
    geom_errorbar(aes(ymax=means+sems, ymin=means-sems),width=.2,position=position_dodge(.9))+
    ggtitle("Optimism Scores by Sex and Political Affiliation")+
    labs(x="Political Party Affiliation",y="Optimism scores")+
    scale_x_discrete(breaks=c("democrat","independent","republican"),labels=c("Democrat","Independent","Republican"))+
    theme(plot.title=element_text(size=15,face="bold",vjust=.5))+
    theme(axis.title.x=element_text(size=12,face="bold",vjust=-.25))+
    theme(axis.title.y=element_text(size=12,face="bold",vjust=1))+
    theme(axis.text.x=element_text(size=10,face="bold",color="black"))+
    theme(axis.text.y=element_text(size=10,face="bold",color="black"))+
    coord_cartesian(ylim=c(min(temp$means)-2*max(temp$sems),max(temp$means)+2*max(temp$sems)))+
    theme(panel.border=element_blank(),axis.line=element_line())+
    theme(panel.grid.major.x=element_blank())+
    theme(panel.grid.major.y=element_line(color="darkgrey"))+
    theme(panel.grid.minor.y=element_blank())+
    theme(legend.position=c(.2,.76))+
    theme(legend.background=element_blank())+
    theme(legend.background=element_rect(color="black"))+
    theme(legend.title=element_blank())+
    theme(legend.title=element_text(size=12))+
    theme(legend.title.align=.5)+
    theme(legend.text=element_text(size=10,face="bold"))
f
```
<!-- Create a line graph for the same data. With
error bars of course!-->
```{r}

f<-ggplot(temp, aes(x=party, y=means, group=sex, color=sex))+
    geom_line(size=1)+
    geom_point(size=2)+
    scale_color_manual(values=c(col1,col2),name="Sex",breaks=c("female","male"),labels=c("Female", "Male"))+
    geom_errorbar(aes(ymax=means+sems, ymin=means-sems),width=.2)+
    ggtitle("OptimismScore by Sex and Political Affiliation")+
    labs(x="Political Party Affiliation",y="Optimism Scores")+
    scale_x_discrete(breaks=c("democrat","independent","republican"),labels=c("Democrat","Independent","Republican"))+
    theme(plot.title=element_text(size=15,face="bold",vjust=.5))+
    theme(axis.title.x=element_text(size=12,face="bold",vjust=-.25))+
    theme(axis.title.y=element_text(size=12,face="bold",vjust=1))+
    theme(axis.text.x=element_text(size=10,face="bold",color="black"))+
    theme(axis.text.y=element_text(size=10,face="bold",color="black"))+
    coord_cartesian(ylim=c(min(temp$means)-2*max(temp$sems),max(temp$means)+2*max(temp$sems)))+
    theme(panel.border=element_blank(),axis.line=element_line())+
    theme(panel.grid.major.x=element_blank())+
    theme(panel.grid.major.y=element_line(color="darkgrey"))+
    theme(panel.grid.minor.y=element_blank())+
    theme(legend.position=c(.2,.76))+
    theme(legend.background=element_blank())+
    theme(legend.background=element_rect(color="black"))+
    theme(legend.title=element_blank())+
    theme(legend.title=element_text(size=12))+
    theme(legend.title.align=.5)+
    theme(legend.text=element_text(size=10,face="bold"))
f
```

<!-- Run a test to see ifoptimism scores pre- and post
watching videos depends on sex.-->
```{r}
summary(aov(optimismscore~testtime*sex+Error(subject/testtime),data=politics))
```




<!-- Run a Multiple Regression Analysis to see
whether you can predict someones posttest optimism
scores from their pretest optimism scores and party
affiliation.-->
```{r}
summary(lm(optimismscore~party,data=politics[politics$testtime=="pre",]))
```
***Fin***

